### ISSUE TITLE
rootinchase.com subdomains exposed to the public?

### ISSUE THREAD

**Issue by Flute7** [rootinchase/Docker#1]
Hi buddy. I stumbled across your site while searching google and many of your services are exposed without proper authentication or even an authorisation portal? 

I can read all of your services logs via Dozzle? I'm assuming this is a mistake?

I understand posting here doesn't help your security but I guess I should tell you.

**Comment by rootinchase** [comment]
Thank you for pointing this out, I will be editing things to prevent that for several of the services. This is outdated currently, but will get updated to a more current setup when that happens.
